/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface TherapistMatch {
  name: string;
  title: string;
  initials: string;
  color: string;
  textColor: string;
  score: string;
  why: string;
  fits: string[];
  profileUrl?: string;
  photoUrl?: string;
}
