/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface ProviderApplicationInput {
  name: string;
  credentials: string;
  email: string;
  specialty: string;
  modalities?: string;
  location?: string;
  telehealth?: string;
  plan: string;
  message?: string;
}
