/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface AnthropicConversation {
  id: number;
  title: string;
  createdAt: string;
}

export interface AnthropicMessage {
  id: number;
  conversationId: number;
  role: string;
  content: string;
  createdAt: string;
}

export interface AnthropicConversationInput {
  title: string;
}

export interface AnthropicMessageInput {
  content: string;
}

export interface AnthropicConversationWithMessages {
  id: number;
  title: string;
  createdAt: string;
  messages: AnthropicMessage[];
}

export interface AnthropicError {
  error: string;
}

export interface TTSRequest {
  text: string;
  voiceId?: string;
  gender?: string;
}

export interface TTSResponse {
  /** Base64-encoded audio data */
  audio: string;
  contentType: string;
}

export interface SageChatMessage {
  role: string;
  content: string;
}

export interface SageChatInput {
  history: SageChatMessage[];
  /** @nullable */
  userMessage?: string | null;
}

export interface SageChatResult {
  reply: string;
  complete: boolean;
}

export interface TherapistMatch {
  name: string;
  title: string;
  initials: string;
  color: string;
  textColor: string;
  score: string;
  why: string;
  fits: string[];
  profileUrl?: string;
  photoUrl?: string;
}

export interface TherapyProfile {
  name: string;
  tagline: string;
  tags: string[];
  challenges: string;
  recommendations: string;
  therapistSummary: string;
  therapists: TherapistMatch[];
}

export interface ProfileInput {
  history: SageChatMessage[];
}

export interface ContactRequestInput {
  therapistName: string;
  therapistProfileUrl?: string;
  userName: string;
  userEmail: string;
  userMessage?: string;
  profileSummary?: string;
}

export interface ContactRequestResult {
  id: number;
  createdAt: string;
}

export interface ProviderApplicationInput {
  name: string;
  credentials: string;
  email: string;
  specialty: string;
  modalities?: string;
  location?: string;
  telehealth?: string;
  plan: string;
  message?: string;
}

export interface ProviderApplicationResult {
  id: number;
  createdAt: string;
}

